apiVersion: v1
kind: Pod

metadata:
  name: volume-pod
  namespace: production
  labels:
    name: volume-pod
spec:
  volumes:
    - name: db-backup-pd
      gcePersistentDisk:
        readOnly: true
        pdName: bp-backup-production-disk

  containers:
  - name: dbinspector
    image: nginx
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /db
        name: db-backup-pd