---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: twitter-ingest-cronjob
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: gcr.io/bootiful/twi-twitter-ingest-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: twi-configmap
          restartPolicy: OnFailure
