apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: postgresql

  selector:
    app: postgresql
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-configmap-volume
          configMap:
            name: postgresql-init-db-configmap
            items:
              - key: "init_db.sh"
                path: "init_db.sh"
      containers:
        - name: postgres
          image: postgres:12.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgresql
          envFrom:
            - secretRef:
                name: postgresql-secrets
          volumeMounts:
            - name: postgresql-configmap-volume
              mountPath: "/docker-entrypoint-initdb.d/"