---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 5672
      name: engine
      protocol: TCP
      targetPort: 5672
    - port: 15672
      name: management
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.9-management
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbitmq-secrets