name: Deploy

env:
  GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE  }}
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT  }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  # SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  # SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  # SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  # SPRING_REDIS_HOST: ${{ secrets.REDIS_HOST }}
  # SPRING_REDIS_PASSWORD: ${{ secrets.REDIS_PW }}
  # SPRING_REDIS_PORT: ${{ secrets.REDIS_PORT }}
  
  ARTIFACTORY_API_TOKEN_SECRET: ${{ secrets.ARTIFACTORY_API_TOKEN_SECRET }} 
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }} 
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }} 
  DB_DB: ${{ secrets.DB_DB }} 
  DB_HOST: ${{ secrets.DB_HOST }} 
  DB_PW: ${{ secrets.DB_PW }} 
  DB_USER: ${{ secrets.DB_USER }} 
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }} 
  GKE_NS: ${{ secrets.GKE_NS }} 
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }} 
  INGEST_INGESTED_TAG: ${{ secrets.INGEST_INGESTED_TAG }} 
  INGEST_TAGS: ${{ secrets.INGEST_TAGS }} 
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }} 
  REDIS_HOST: ${{ secrets.REDIS_HOST }} 
  REDIS_PORT: ${{ secrets.REDIS_PORT }} 
  REDIS_PW: ${{ secrets.REDIS_PW }} 
  TWITTER_TWI_CLIENT_KEY: ${{ secrets.TWITTER_TWI_CLIENT_KEY }} 
  TWITTER_TWI_CLIENT_KEY_SECRET: ${{ secrets.TWITTER_TWI_CLIENT_KEY_SECRET }} 
  TWI_PREFIX: ${{ secrets.TWI_PREFIX }} 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          export_default_credentials: true

      - run: |
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project ${GCLOUD_PROJECT}

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          ./deploy.sh